main:
  - name: Description
    url: /description/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Content
    url: /content/
    weight: 3
  - name: Tutorials
    url: /tutorials/
    weight: 4
  - name: Resources
    url: /resource/
    weight: 5

content:
  - name: Overview
    weight: 1
  - name: Course content
    weight: 2
tutorials:
  - name: Overview
    weight: 1
  - name: Tutorials
    weight: 2
resource:
  - name: Resources
    weight: 1
  - name: Guides
    weight: 2
